### ISSUE TITLE
خطا در کنسول بعد از انتخاب تاریخ

### ISSUE THREAD

**Issue by mmhashemi** [Mds92/MD.BootstrapPersianDateTimePicker#271]
سلام وقت بخیر 
از آخرین نسخه متناسب با بوت استرپ 5 استفاده میکنم 
وقتی پنل تاریخ باز میشه و تاریخی رو انتخاب میکنم در کنسول خطا میزنه و بعد از اون تاریخ دیگه ای رو انتخاب میکنم در باکس مورد نظر تاریخ رو درج میکنه اما تاریخ قبلی همچنان استایل انتخاب داره و از انتخاب خارج نمیشه و هر تاریخ دیگه ای هم انتخاب کنم همین جریان هست و هیچ تاریخی از انتخاب خارج نمیشه
اینم نمونه کد و نحوه استفاده ام هست 

```

		let elem = document.getElementById('bt_dtp');

        const dtp1 = 
           new  mds.MdsPersianDateTimePicker(elem, {
                targetTextSelector: '#input_dtp',
                isGregorian: false,
                persianNumber : true
            });
```

اینم خطایی که در کنسول نمایش داده میشه 

```
2selector-engine.js:24 Uncaught TypeError: Illegal invocation
    at Object.findOne (selector-engine.js:24:44)
    at Je._sanitizeAndSetContent (tooltip.js:386:44)
    at Je.setContent (popover.js:88:10)
    at r.updateCalendarBodyHtml (mds.bs.datetimepicker.js:9:3401)
    at r.selectDay (mds.bs.datetimepicker.js:9:7131)
    at HTMLDocument.selectCorrectClickEvent (mds.bs.datetimepicker.js:9:10358)
```

**Comment by Mds92** [comment]
سلام، آیا در فایل دمو هم همین مشکل هست؟

**Comment by mmhashemi** [comment]
سلام خیر در دمو من این مورد رو ندیدم.  به چیزی احتمال میدید که دلیل این خطا باشه ؟ تفاوت ورژن بوت استرپ در حد 0.0.1 فکر کنم داریم که البته بعید میدونم دلیل این مشکل باشه.
ممنون میشم اگه مقدوره راهنمایی بفرماییدو متشکرم

**Comment by EmadMi** [comment]
برای من هم همین مشکل پیش میاد.
راه حلی نداره؟

**Comment by vahidalvandi** [comment]
وقتی ۲ بار روی باکس انتخاب تاریخ زده میشه در پایین صفحه با عرض کامل تقویم باز میشه و از حالت پاپ اپ خارج میشه

**Comment by vahidalvandi** [comment]
> سلام خیر در دمو من این مورد رو ندیدم. به چیزی احتمال میدید که دلیل این خطا باشه ؟ تفاوت ورژن بوت استرپ در حد 0.0.1 فکر کنم داریم که البته بعید میدونم دلیل این مشکل باشه. ممنون میشم اگه مقدوره راهنمایی بفرماییدو متشکرم

من از نسخه 5.2 استفاده میکنم فکر کنم مشکل از نسخه بوتسترپ باشد

**Comment by aliajboy** [comment]
برای منم این مشکل هست. از قالب بوت استرپ 5 "Sneat" استفاده میکنم. بوت استرپ های مختلف هم تست کردم مشکل وجود داره. تا زمانی که input خالیه مشکلی نیست و تنها ورودی اولیه به راحتی وارد میشه. اما دیگه نمیشه تغییرش داد!
اینم بگم که من توی کنسول هیچ خطایی ندارم ولی اینجوریه. توی دمو با نسخه بوت استرپ من مشکلی نبود.

**Comment by aliajboy** [comment]
دوستان من مشکلو پیدا کردم ولی راه حلی هنوز پیدا نکردم. من توی ASP.Net دارم ازش استفاده میکنم و دیتا رو با تگ asp-for میگرفتم که id و name رو خودش میده. وقتی آی دی و نیم رو دستی میدم کار میده! ولی از آی دی و نیم خودش استفاده کنم کار نمیده. باز تلاش میکنم اگر چیزی کمک کرد اعلام میکنم
