### ISSUE TITLE
toJalaali is not defined

### ISSUE THREAD

**Issue by Number30** [Mds92/MD.BootstrapPersianDateTimePicker#50]
hi..
i use it in my project with angular 2 and using webpack for publish and i faced to this error :

Error: Uncaught (in promise): Error: Error in :0:0 caused by: toJalaali is not defined
ReferenceError: toJalaali is not defined
    at getTodayCalendarInPersian (http://localhost:3000/dist/3.fe78e1c59da123fedf2a.chunk.js:4102:21)
    at parsePersianDateTime (http://localhost:3000/dist/3.fe78e1c59da123fedf2a.chunk.js:4490:27)
    at HTMLInputElement.<anonymous> (http://localhost:3000/dist/3.fe78e1c59da123fedf2a.chunk.js:5485:41)
    at Function.each (http://localhost:3000/dist/vendor4.fe78e1c59da123fedf2a.bundle.js:377:19)
    at webpackJsonp.774.a.fn.init.each (http://localhost:3000/dist/vendor4.fe78e1c59da123fedf2a.bundle.js:172:17)
    at webpackJsonp.774.a.fn.init.init (http://localhost:3000/dist/3.fe78e1c59da123fedf2a.chunk.js:5456:19)
    at webpackJsonp.774.a.fn.init.webpackJsonp.1761.$.fn.MdPersianDateTimePicker (http://localhost:3000/dist/3.fe78e1c59da123fedf2a.chunk.js:5574:27)
    at LoginLogComponent.webpackJsonp.1436.LoginLogComponent.ngOnInit (http://localhost:3000/dist/3.fe78e1c59da123fedf2a.chunk.js:1747:30)
    at Wrapper_LoginLogComponent.ngDoCheck (/SecurityModule/LoginLogComponent/wrapper.ngfactory.js:24:53)
    at CompiledTemplate.proxyViewClass.View_LoginLogComponent_Host0.detectChangesInternal (/SecurityModule/LoginLogComponent/host.ngfactory.js:28:31)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:3000/dist/vendor1.fe78e1c59da123fedf2a.bundle.js:60119:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:3000/dist/vendor1.fe78e1c59da123fedf2a.bundle.js:60314:44)
    at ViewRef_.detectChanges (http://localhost:3000/dist/vendor1.fe78e1c59da123fedf2a.bundle.js:42788:20)
    at RouterOutlet.activate (http://localhost:3000/dist/vendor1.fe78e1c59da123fedf2a.bundle.js:55682:42)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:3000/dist/vendor1.fe78e1c59da123fedf2a.bundle.js:20426:16)
    at getTodayCalendarInPersian (http://localhost:3000/dist/3.fe78e1c59da123fedf2a.chunk.js:4102:21)
    at parsePersianDateTime (http://localhost:3000/dist/3.fe78e1c59da123fedf2a.chunk.js:4490:27)
    at HTMLInputElement.<anonymous> (http://localhost:3000/dist/3.fe78e1c59da123fedf2a.chunk.js:5485:41)
    at Function.each (http://localhost:3000/dist/vendor4.fe78e1c59da123fedf2a.bundle.js:377:19)
    at webpackJsonp.774.a.fn.init.each (http://localhost:3000/dist/vendor4.fe78e1c59da123fedf2a.bundle.js:172:17)
    at webpackJsonp.774.a.fn.init.init (http://localhost:3000/dist/3.fe78e1c59da123fedf2a.chunk.js:5456:19)
    at webpackJsonp.774.a.fn.init.webpackJsonp.1761.$.fn.MdPersianDateTimePicker (http://localhost:3000/dist/3.fe78e1c59da123fedf2a.chunk.js:5574:27)
    at LoginLogComponent.webpackJsonp.1436.LoginLogComponent.ngOnInit (http://localhost:3000/dist/3.fe78e1c59da123fedf2a.chunk.js:1747:30)
    at Wrapper_LoginLogComponent.ngDoCheck (/SecurityModule/LoginLogComponent/wrapper.ngfactory.js:24:53)
    at CompiledTemplate.proxyViewClass.View_LoginLogComponent_Host0.detectChangesInternal (/SecurityModule/LoginLogComponent/host.ngfactory.js:28:31)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:3000/dist/vendor1.fe78e1c59da123fedf2a.bundle.js:60119:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:3000/dist/vendor1.fe78e1c59da123fedf2a.bundle.js:60314:44)
    at ViewRef_.detectChanges (http://localhost:3000/dist/vendor1.fe78e1c59da123fedf2a.bundle.js:42788:20)
    at RouterOutlet.activate (http://localhost:3000/dist/vendor1.fe78e1c59da123fedf2a.bundle.js:55682:42)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:3000/dist/vendor1.fe78e1c59da123fedf2a.bundle.js:20426:16)
    at resolvePromise (http://localhost:3000/dist/polyfills.fe78e1c59da123fedf2a.bundle.js:9539:31) [angular]
    at resolvePromise (http://localhost:3000/dist/polyfills.fe78e1c59da123fedf2a.bundle.js:9524:17) [angular]
    at http://localhost:3000/dist/polyfills.fe78e1c59da123fedf2a.bundle.js:9573:17 [angular]
    at Object.onInvokeTask (http://localhost:3000/dist/vendor1.fe78e1c59da123fedf2a.bundle.js:22553:37) [angular]
    at ZoneDelegate.invokeTask (http://localhost:3000/dist/polyfills.fe78e1c59da123fedf2a.bundle.js:9327:40) [angular]
    at Zone.runTask (http://localhost:3000/dist/polyfills.fe78e1c59da123fedf2a.bundle.js:9204:47) [<root> => angular]
    at drainMicroTaskQueue (http://localhost:3000/dist/polyfills.fe78e1c59da123fedf2a.bundle.js:9471:35) [<root>]
    at <anonymous> [<root>]

how could i resolve it ?
thanks for any help

**Comment by Mds92** [comment]
Actually, I don't know what is your problem,
I didn't develop it for angular 2
You have to use the following library for Angular 4
https://github.com/Mds92/mds-angular-datetime-picker-package

**Comment by Number30** [comment]
thanks for your suggestion

**Comment by Mds92** [comment]
Remember, I'm developing `mds-angular-datetime-picker-package`
Check latest version daily
